server:
  host: 0.0.0.0
  port: 2022
  readTimeout: 60s
  writeTimeout: 60s
  tokenExpiretime: 2073600 #token过期时间，单位秒

database:
  type: mysql
  host: 127.0.0.1
  port: 3306
  user: root
  password: root
  dbname: sblog
  charset: utf8mb4
  prefix: sb_
  timeout: 30s

encryption:
  key: c0f29a4f0320340bbe0b23d22898ba67